language: cpp

os:
    - linux
    - osx

dist: trusty

compiler:
    - gcc
    - clang

addons:
   apt:
      packages:
      - libboost-dev

before_script:
    - $CXX --version
    - ls /usr/bin/gcc*
    - cmake --version

script:
    - cmake -DCMAKE_BUILD_TYPE=Release .
    - make -j2

notifications:
    email: false
